#!/usr/bin/env python3
"""Refresh docs/benchmark.md and the GA4GH summary table in README.md from JSON artefacts."""
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--metrics", required=True)
    ap.add_argument("--benchmark", required=True)
    ap.add_argument("--readme", required=True)
    ap.add_argument("--bench-md", required=True)
    ap.add_argument(
        "--repo-root",
        default=None,
        help="Repository root (for synthetic vs real dataset label); defaults to parent of scripts/",
    )
    args = ap.parse_args()

    metrics = json.loads(Path(args.metrics).read_text())
    bench = json.loads(Path(args.benchmark).read_text())
    root = Path(args.repo_root or Path(__file__).resolve().parents[1])
    interval_txt = root / "results" / "interval.txt"
    interval = (
        interval_txt.read_text().strip()
        if interval_txt.is_file()
        else "chr22 (see results/interval.txt)"
    )
    if (root / "data" / "synthetic_manifest.txt").is_file():
        dataset = f"Synthetic GIAB-style subset ({interval})"
    else:
        dataset = (
            "NA12878 Platinum slice + GIAB HG001 truth (GRCh37), "
            f"{interval}"
        )

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    summary_src = bench.get("summary_source") or bench.get("summary_json", "n/a")
    try:
        sp = Path(str(summary_src))
        if sp.is_absolute():
            summary_src = str(sp.relative_to(root.resolve()))
    except (ValueError, OSError):
        pass

    dm = metrics.get("drs_micro") or {}
    plain_w = (dm.get("plain") or {}).get("wall_seconds") or {}
    plain_med = plain_w.get("median") if isinstance(plain_w, dict) else None
    crypt = dm.get("crypt4gh")
    crypt_line = ""
    if isinstance(crypt, dict) and not crypt.get("skipped") and not crypt.get("error"):
        cw = crypt.get("wall_seconds") or {}
        if isinstance(cw, dict) and cw.get("median") is not None:
            crypt_line = f"| DRS /stream Crypt4GH median (s) | {cw.get('median')} |\n"
    engine = metrics.get("wes_engine", "wdl")

    bench_md = f"""# Benchmark (hap.py)

Auto-generated by `demo/run.sh` — **do not hand-edit** (regenerated on each pipeline run).

| Field | Value |
|-------|-------|
| Last run | {now} |
| Pipeline wall time (s) | {metrics.get("pipeline_elapsed_seconds", "n/a")} |
| WES engine | {engine} |
| WES run id | `{metrics.get("wes_run_id", "n/a")}` |
| DRS /stream plain median (s, ref_fasta) | {plain_med if plain_med is not None else "n/a"} |
{crypt_line}| Precision | {bench.get("precision")} |
| Recall | {bench.get("recall")} |
| F1 | {bench.get("f1_score")} |
| Input dataset | {dataset} |
| hap.py metrics | `{summary_src}` |

## GA4GH components exercised

1. **TRS** — Dockstore `ga4gh/trs/v2` descriptor cached under `workflows/cached/`.
2. **DRS** — Files ingested via `POST /ga4gh/drs/v1/ingest/file`; Cromwell localizes `GET .../objects/{{id}}/stream` (raw bytes on the compose network).
3. **WES** — `POST /ga4gh/wes/v1/runs` (WDL or Nextflow + params).
4. **TES** — Ferrum routes WES to `POST /ga4gh/tes/v1/tasks` (Docker backend: Cromwell + nested GATK, or Nextflow + `-with-docker`).
5. **DRS micro** — `scripts/drs_micro_benchmark.py` times `GET .../objects/{{id}}/stream` (optional `X-Crypt4GH-Public-Key`); see `results/drs_micro.json`.
"""
    Path(args.bench_md).parent.mkdir(parents=True, exist_ok=True)
    Path(args.bench_md).write_text(bench_md)

    readme = Path(args.readme).read_text()
    table = f"""| Metric | Value |
|--------|-------|
| Precision | {bench.get("precision")} |
| Recall | {bench.get("recall")} |
| F1 | {bench.get("f1_score")} |
| Runtime (demo) | {metrics.get("pipeline_elapsed_seconds", "n/a")} s |
| WES engine | {engine} |
| DRS stream (median s) | {plain_med if plain_med is not None else "n/a"} |
| WES run | `{metrics.get("wes_run_id", "n/a")}` |
"""
    start = "<!-- GA4GH_BENCHMARK_TABLE_START -->"
    end = "<!-- GA4GH_BENCHMARK_TABLE_END -->"
    if start in readme and end in readme:
        pre, rest = readme.split(start, 1)
        mid, post = rest.split(end, 1)
        readme = f"{pre}{start}\n{table}\n{end}{post}"
    else:
        readme += f"\n\n{start}\n{table}\n{end}\n"
    Path(args.readme).write_text(readme)


if __name__ == "__main__":
    main()
